### PR TITLE
Issue17: JWT Authentication System

### PR DESCRIPTION
**Pull request by DannyPeck**
Created a JWT based authentication system which follows the 'bearer token' strategy.  To login, clients will send a POST request to /login with their username and password as the body.  This will return a JWT. 

Clients will now have access to authenticated routes by adding the header "Authorization": 'bearer token' in their requests.

### CODE REVIEW

**Comment by DannyPeck** [comment]
Travis-CI is failing due to not being integrated into this branch.

**Comment by najowhit** [comment]
Line 46 of UserController.js: 

`var secret = blueprint.app.configs.server.middleware.jwt.secret;`

What is the reason for having to include the "middleware" here?

**Comment by DannyPeck** [comment]
The reason for having middleware in there, is that we have stored the server-secret in the server.config.js file and are reading it programmatically.  Since that is where it is nested in the server.config.js file I have to include those in order to read it.

**Comment by DannyPeck** [comment]
Note, I have had to add the token to the User Model in order to follow the recommended bearer authentication strategy.

**Pull request merged**
